apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - persistent-volume-claim.yaml
  - migration-job.yaml
  - stateful-set.yaml
  - service.yaml
  - probe-service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: identityd
      app.kubernetes.io/part-of: ctlflow-kernel
