<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>CtlFlow.Configuration.Configd.IntegrationTests</AssemblyName>
    <RootNamespace>CtlFlow.Configuration.Configd.IntegrationTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <SelfContained>true</SelfContained>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <TrimmerTreatWarningsAsErrors>true</TrimmerTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>false</SuppressAotAnalysisWarnings>
    <SuppressSingleFileAnalysisWarnings>false</SuppressSingleFileAnalysisWarnings>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CtlFlow.Configuration.Configd.Db/CtlFlow.Configuration.Configd.Db.csproj" />
  </ItemGroup>
</Project>
