<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CtlFlow.Auth.Authd.Service</AssemblyName>
    <RootNamespace>CtlFlow.Auth.Authd.Service</RootNamespace>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <SelfContained>true</SelfContained>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <TrimmerTreatWarningsAsErrors>true</TrimmerTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>false</SuppressAotAnalysisWarnings>
    <SuppressSingleFileAnalysisWarnings>false</SuppressSingleFileAnalysisWarnings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CtlFlow.Auth.Authd.Domain/CtlFlow.Auth.Authd.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="../../../../identityd/api/proto/v1/identityd.proto"
              GrpcServices="Client"
              ProtoRoot="../../../../identityd/api/proto" />
    <Protobuf Include="../../../../tenantd/api/proto/v1/tenantd.proto"
              GrpcServices="Client"
              ProtoRoot="../../../../tenantd/api/proto" />
  </ItemGroup>
</Project>
