<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CtlFlow.Egress.Egressd.Service</AssemblyName>
    <RootNamespace>CtlFlow.Egress.Egressd.Service</RootNamespace>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <SelfContained>true</SelfContained>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <TrimmerTreatWarningsAsErrors>true</TrimmerTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>false</SuppressAotAnalysisWarnings>
    <SuppressSingleFileAnalysisWarnings>false</SuppressSingleFileAnalysisWarnings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CtlFlow.Egress.Egressd.Domain/CtlFlow.Egress.Egressd.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
</Project>
