<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CtlFlow.Configuration.Configd.Service</AssemblyName>
    <RootNamespace>CtlFlow.Configuration.Configd.Service</RootNamespace>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <SelfContained>true</SelfContained>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <TrimmerTreatWarningsAsErrors>true</TrimmerTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>false</SuppressAotAnalysisWarnings>
    <SuppressSingleFileAnalysisWarnings>false</SuppressSingleFileAnalysisWarnings>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
    <EFScaffoldModelStage>none</EFScaffoldModelStage>
    <EFPrecompileQueriesStage>none</EFPrecompileQueriesStage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CtlFlow.Configuration.Configd.Domain/CtlFlow.Configuration.Configd.Domain.csproj" />
    <ProjectReference Include="../CtlFlow.Configuration.Configd.Db/CtlFlow.Configuration.Configd.Db.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tasks" PrivateAssets="all" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="../../../api/proto/v1/configd.proto"
              GrpcServices="Server"
              ProtoRoot="../../../api/proto" />
    <Protobuf Include="../../../../auditd/api/proto/v1/auditd.proto"
              GrpcServices="Client"
              ProtoRoot="../../../../auditd/api/proto" />
    <Protobuf Include="../../../../identityd/api/proto/v1/identityd.proto"
              GrpcServices="Client"
              ProtoRoot="../../../../identityd/api/proto" />
    <Protobuf Include="../../../../policyd/api/proto/v1/policyd.proto"
              GrpcServices="Client"
              ProtoRoot="../../../../policyd/api/proto" />
  </ItemGroup>
</Project>
