apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - persistent-volume-claim.yaml
  - migration-job.yaml
  - stateful-set.yaml
  - service.yaml
  - probe-service.yaml
configMapGenerator:
  - name: policyd-policy
    files:
      - policy-seed.json
labels:
  - pairs:
      app.kubernetes.io/name: policyd
      app.kubernetes.io/part-of: ctlflow-kernel
